<body>

<div id="registration" class="container">
        <fieldset>
            <h2> Mes Informations Personnels </h2><br>
            <label style="font-size: 20px;">Prenom : <?php $firstname = $this->setInfoFirstname($_SESSION["id_user"]); echo($firstname); ?></label><br>
            <label style="font-size: 20px;">Nom : <?php $lastname = $this->setInfoLastname($_SESSION["id_user"]); echo($lastname); ?></label><br>
            <label style="font-size: 20px;">Date de naissance : <?php $birthdate = $this->setInfoBirthdate($_SESSION["id_user"]); echo($birthdate); ?></label><br>
            <br>
        <form method="post" action="index.php/collab/modifPhone">
            <label style="font-size: 20px;">Numero de telephone : <?php $phone = $this->setInfoPhone($_SESSION["id_user"]); echo('0'.$phone); ?></label><br>
            <label> Nouveau Numero : </label><br>
            <input type="tel" name="phoneNumber" pattern="0[1-68]([-. ]?[0-9]{2}){4}" title="Le numero de téléphone doit contenir 10 chiffres."><br>
            <input id="button" type="submit" name="modifPhone" value="Modifier"><br><br>
        </form>
        <form method="post" action="index.php/collab/modifMail">
            <label style="font-size: 20px;">E-mail : <?php $mail = $this->setInfoMail($_SESSION["id_user"]); echo($mail); ?></label><br>
            <label> Nouveau Mail : </label><br>
            <input type="email" name="mail"><br>
            <input id="button" type="submit" name="modifMail" value="Modifier"><br><br>
        </fieldset>
    </form>
</div>

