<body>

<div id="registration" class="container">
    <form method="post">
        <fieldset>
            <h1> Mes Informations Personnels </h1><br>
            <label>Prenom : <?php $firstname = $this->setInfoFirstname($_SESSION["id_user"]); echo($firstname); ?></label><br>
            <br>
            <label>Nom : <?php $lastname = $this->setInfoLastname($_SESSION["id_user"]); echo($lastname); ?></label><br>
            <br>
            <label>Date de naissance : <?php $birthdate = $this->setInfoBirthdate($_SESSION["id_user"]); echo($birthdate); ?></label><br>
            <br>
            <label>Numero de telephone : <?php $phone = $this->setInfoPhone($_SESSION["id_user"]); echo('0'.$phone); ?></label><br>
            <br>
            <label>E-mail : <?php $mail = $this->setInfoMail($_SESSION["id_user"]); echo($mail); ?></label><br>
            <br>
            <input id="button" type="submit" name="registration" value="Modifier"><br><br>
            <input id="button" type="reset" value="Annuler"><br>
        </fieldset><br><br>
    </form>
</div>

