<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php echo $result1;?>
    <?php echo $result2;?>
    <table id="presence">
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>N° de téléphone</th>
            <th>Formation</th>
            <th> Emargement</th>
        </tr>
        <?php echo $result;?>
    </table>
    <br>
</body>
</html>
