<h2 style="width: 50%;margin-left:auto;margin-right:auto;">Liste des utilisateurs</h2><br>

<div id="listUser">
    <a href="../admin/animManagement" style="width: 50%;margin-left:auto;margin-right:auto;text-align:center;"><button class="btn-hover color-1" style="text-decoration: none; color: black; font-size: 20px;margin-right:0;margin-left:0">Liste Animateur</button></a>
    <br><br>
    <a href="../admin/collabManagement" style ="width: 50%;margin-left:auto;margin-right:auto;"><button class="btn-hover color-1" style="text-decoration: none; color: black; font-size: 20px;margin-right:0;margin-left:0">Liste Collaborateur</button></a>
</div>