<br><br>
<h2>Liste Etudiant </h2><br>
    <form method="post" id="form1" enctype="multipart/form-data" multiple>
        <table id="listCollab">
                <tr>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>N° de téléphone</th>
                    <th>Mail</th>
                    <th> Supprimer <input type="checkbox" id="check_all"></th>
                </tr>
                <?php echo $this->_listCollab; ?>
        </table><br></br>
        <input id="inputSubmit" style="width: 15%; background-color:red;" type = "submit" value = "Supprimer" name="deleteUser"><br></br>
    </form>
<a id="inputSubmit" style="text-decoration: none; margin-left: 10%;" href="../../index.php/admin/accountManagement"> Retour </a>

<!-- Jquery -->
<script>
$(document).ready(function(){
    var cc = document.getElementById('check_all');
    $(cc).on('click', function(){
        if (cc.checked){
            $('input[type=checkbox]').prop('checked', true);
        } else {
            $('input[type=checkbox]').prop('checked', false);
        }
    });
});
</script>