<br><br>
<h2>Liste Collaborateur </h2><br>
    <p style="margin-left: 10%;"> Attention, supprimer un collaborateur risque de corrompre son archivage d'activité !</p><br>
    
    <form method="post" id="form1" enctype="multipart/form-data" multiple>
        <table id="listCollab">
                <tr>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>N° de téléphone</th>
                    <th>Mail</th>
                    <th>Formation</th>
                    <th>Supprimer</th>
                </tr>
                <?php echo $this->_collabList; ?>
        </table><br>
    </form>

<a id="inputSubmit" style="text-decoration: none; margin-left: 10%;" href="../../index.php/admin/accountManagement"> Retour </a>
