<body>
    <div id="title" class="container">
    <h2>Création d'un Thème</h2>
    </div>

<div id="registration" class="container">
    <form method="post">
        <fieldset>
            <label>Nom du thème :</label> 
            <input type="text" name="name" required><br><br>

            <label>Choix de la couleur du thème :</label>
            <input type="color" value="#fad345" name="color" required><br><br>

            <label>Description :</label>
            <input type="text" name="description" required><br><br>

            <label>Description détaillée :</label>
            <textarea name="detailedDescription" cols="40" rows="5" required></textarea><br><br>

            <label>Animateur du thème</label>
            <select name="referAnimator"><br><br>
                <?php echo $this->_userList;?>
            </select><br><br>

            <input id="button" type="submit" name="createTheme" value="Valider"><br><br>
            <input id="button" type="reset" value="Annuler">
        </fieldset>
    </form>
</div>