<body>
    <div id="title" class="container">
    <h2>Création d'une formation</h2>
    </div>

<div id="registration" class="container">
    <form id="form2" method="post">
        <fieldset>
            <label>Nom de la formation :</label> 
            <input type="text" name="name" required><br><br>

            <input id="button" type="submit" name="createFormation" value="Valider"><br><br>
            <input id="button" type="reset" value="Annuler">
        </fieldset>
    </form>
</div>