<body>
    <div id="title">
    <h2>Création d'une Activité</h2>
    </div>

<div id="registration">
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <label>Thème associé :</label> 
            <div style="background-color:<?php echo $_GET['colorTheme'];?>;border-radius:5px;width:20%;margin-left:40%">
                <?php echo $_GET['nTheme'];?>
            </div><br>

            <label>Nom de l'activité :</label> 
            <input type="text" name="name" required><br><br>

            <label>Description de l'activité:</label><br>
            <textarea name="description" cols="40" rows="5" required></textarea><br><br>

            <label>Description détaillée de l'activité:</label><br>
            <textarea name="detailedDescription" cols="40" rows="5" required></textarea><br><br>

            <label>Image :</label>
            <input class="upload" type="file" name="image"><br><br>

            <input id="inputSubmit" style="width: 20%;" type="submit" name="createActivity" value="Valider"><br><br>
            <input id="inputSubmit" style="width: 20%;" type="reset" value="Annuler">
            <a href="javascript:history.back()"><input id="inputSubmit" style="width: 20%;" value="Retour"></a>
        </fieldset>
    </form>
</div>