<body>
    <div id="title">
    <h2>Création d'une formation</h2>
    </div>

<div id="registration">
    <form method="post">
        <fieldset>
            <label>Nom de la formation :</label> 
            <input type="text" name="name" required><br><br>

            <input id="inputSubmit" style="width: 20%;" type="submit" name="createFormation" value="Valider"><br><br>
            <input id="inputSubmit" style="width: 20%;" type="reset" value="Annuler">
        </fieldset>
    </form>
</div>