<body>
    <div id="title">
    <h2>Création d'une Session de formation</h2>
    </div>

<div id="registration">
    <form method="post">
        <fieldset>      
            <label>Formation associé :</label> 
                    <?php echo $_GET['nTraining'];?>
            <br><br>
            <label>Numéro de la Session :</label> 
            <input type="number" name="sessionNumber" required><br><br>

            <label>Début de Formation :</label>
            <input type="date" name="startDateFormation" required><br><br>

            <label>Fin de Formation :</label>
            <input type="date" name="endDateFormation" required><br><br>

            <label>Début de la première PAE :</label>
            <input type="date" name="startDatePae1" required><br><br>            
            
            <label>Fin de la première PAE :</label>
            <input type="date" name="endDatePae1" required><br><br>

            <label>Début de la deuxième PAE :</label>
            <input type="date" name="startDatePae2"><br><br>            
            
            <label>Fin de la deuxième PAE :</label>
            <input type="date" name="endDatePae2"><br><br>

            <label>Début de la troisième PAE :</label>
            <input type="date" name="startDatePae3"><br><br>            
            
            <label>Fin de la troisième PAE :</label>
            <input type="date" name="endDatePae3"><br><br>

            <input id="inputSubmit" style="width: 20%;" type="submit" name="createSession" value="Valider"><br><br>
            <input id="inputSubmit" style="width: 20%;" type="reset" value="Annuler">
        </fieldset>
    </form>
</div>