<body>
    <div id="title">
    <h2>Création d'un Thème</h2>
    </div>

<div id="registration">
    <form method="post">
        <fieldset>
            <label>Nom du thème :</label> 
            <input type="text" name="name" required><br><br>

            <label>Choix de la couleur du thème :</label>
            <input type="color" value="#fad345" name="color" required><br><br>

            <label>Description du thème :</label><br>
            <textarea name="description" cols="40" rows="5" required></textarea><br><br>

            <label>Description détaillée du thème :</label><br>
            <textarea name="detailedDescription" cols="40" rows="5" required></textarea><br><br>

            <label>Animateur du thème</label>
            <select name="referAnimator"><br><br>
                <?php echo $this->_userList;?>
            </select><br><br>

            <input id="inputSubmit" style="width: 20%;" type="submit" name="createTheme" value="Valider"><br><br>
            <input id="inputSubmit" style="width: 20%;" type="reset" value="Annuler">
        </fieldset>
    </form>
</div>