<body>
    <div id="title" class="container">
    <h2>Création d'une Activité</h2>
    </div>

<div id="registration" class="container">
    <form method="post" id="form2" enctype="multipart/form-data">
        <fieldset>
            <label>Thème associé :</label> 
            <select name="nTheme"><br><br>
                <?php echo $this->_themeList;?>
            </select><br><br>

            <label>Nom de l'activité :</label> 
            <input type="text" name="name" required><br><br>

            <label>Description :</label>
            <input type="text" name="description" required><br><br>

            <label>Description détaillée :</label>
            <textarea name="detailedDescription" cols="40" rows="5" required></textarea><br><br>

            <label>Image :</label>
            <input class="upload" type="file" name="image"><br><br>

            <input id="button" type="submit" name="createActivity" value="Valider"><br><br>
            <input id="button" type="reset" value="Annuler">
        </fieldset>
    </form>
</div>