<div id="infoslot">
<form method="post">
    <fieldset>
        <div id="infodesc"><?php echo $this->_infoSession; ?></div>
        <input id="inputSubmit" style="width: 20%;" type="submit" name="updateSession" value="Modifier"><br><br>
    </fieldset>
</form>
</div>

<form method="post">
    <input id="inputSubmit" style="background-color:red; width: 21%; margin-left: 15%;" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer cette session de formation?')" name="deleteSession" value = "Supprimer la session de formation">
</form><br><br>

<a id="inputSubmit"  style='text-decoration: none; margin-left: 15%;' href="../../index.php/admin/listTraining"> Retour </a><br><br>
<body>