<div id="infoslot">
<form method="post" enctype="multipart/form-data">
    <fieldset>
        <div id="infodesc"><?php echo $this->_infoActivity; ?></div>
        <input id="inputSubmit" style="width: 20%;" type="submit" name="updateActivity" value="Modifier"><br><br>
    </fieldset>
</form>
</div><br></br>


<a id="inputSubmit" href="../../index.php/admin/dashboard"> Retour </a><br><br>
<form method="post">
    <input id="inputSubmit" style="background-color:red;" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer ce thème?')" name="deleteTheme" value = "Supprimer le thème">
</form>
<body>




