<div id="infoslot">
<form method="post">
    <fieldset>
        <div id="infodesc"><?php echo $this->_infoTheme; ?></div>
        <input id="inputSubmit" style="width: 17%; font-size: 18px;" type="submit" name="updateTheme" value="Modifier">
    </fieldset>
</form>
</div>

<form method="post">
    <input id="inputSubmit" style="background-color:red; width: 15%; margin-left: 15%;" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer ce thème?')" name="deleteTheme" value = "Supprimer le thème">
</form><br><br>

<a id="inputSubmit" style="text-decoration: none; margin-left: 15%;" href="../../index.php/admin/listTheme"> Retour </a>
<body>




