<div id="infoslot">
<form method="post" enctype="multipart/form-data">
    <fieldset>
        <div id="infodesc"><?php echo $this->_infoActivity; ?></div>
        <input id="inputSubmit" style="width: 20%;" type="submit" name="updateActivity" value="Modifier">
    </fieldset>
</form>
</div>

<form method="post">
    <input id="inputSubmit" style="background-color:red; width: 12%; margin-left: 15%;" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer ce thème?')" name="deleteTheme" value = "Supprimer l'activité">
</form><br><br>

<a id="inputSubmit" style='text-decoration: none; margin-left: 15%;' href="../../index.php/admin/dashboard"> Retour </a>





