<div id="infoslot">
<form method="post">
    <fieldset>
        <div id="infodesc"><?php echo $this->_infoTraining; ?></div>
        <input id="inputSubmit" style="width: 20%;" type="submit" name="updateTraining" value="Modifier"><br><br>
    </fieldset>
</form>
</div><br></br>


<a id="inputSubmit" href="../../index.php/admin/dashboard"> Retour </a><br><br>
<form method="post">
    <input id="inputSubmit" style="background-color:red;" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer cette session de formation?')" name="deleteTraining" value = "Supprimer la formation">
</form>
<body>