<div id="infoslot">
    <div id="infodesc"><?php echo $this->_infoTheme; ?></div>
<div><br></br>


<a id="inputSubmit" href="../../index.php/admin/dashboard"> Retour </a><br><br>

<form method="post">
<input id="inputSubmit" style="background-color:red;" type="submit" name="updateTheme" value = "Modifier le thème">
    <input id="inputSubmit" style="background-color:red;" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer ce thème?')" name="deleteTheme" value = "Supprimer le thème">
</form>