<body>
    <div id="title" class="container">
        <h1>Liste des Thèmes</h1><br>
    </div>

    
    <section id="dashboard">
        <?php echo $this->_listTheme ?>
    </section>
    <p id="inputSubmit" style="margin-left: auto;margin-right: auto;width: 20em;padding-top:1%;padding-bottom:1%">
        <a style="text-decoration:none;color:white" href="../../index.php/admin/createTheme"> Créer un nouveau thème </a>
    </p>
