<body>
    <div id="title" class="container">
        <h1>Liste des Session de formation</h1><br>
    </div>

    
    <section id="dashboard">
        <article>
            <?php echo $this->_sessionList ?>
        </article>
        <br><br><br><br><br><br><br><br><br><br>
    </section>
    <a id="inputSubmit" href="../../index.php/admin/createSession"> Créer une nouvelle session de formation </a><br><br> 