<body>
    <div id="title" class="container">
        <h1>Liste des Formations</h1><br>
    </div>

    
    <section id="dashboard">
        <article>
            <?php echo $this->_trainingList ?>
        </article>
        <br><br><br><br><br><br><br><br><br><br>
    </section>
    <a id="inputSubmit" href="../../index.php/admin/createFormation" style="width:20%;text-align: center;margin-left:40%" > Créer une nouvelle formation</a><br><br> 