<body>
    <div id="title" class="container">
        <h1>Liste des activités pour le thème "<?php echo $this->_nameTheme ?>"</h1><br>
    </div>

    
    <section id="dashboard">
        <article>
            <?php echo $this->_listActivity ?>
        </article>
        <br><br><br><br><br><br><br><br><br><br>
    </section>
    <a href="./createActivity"><input id="inputSubmit" style="width: 20%;text-align: center;margin-left:40%" value="Créer une nouvelle activité"></a><br><br>
