<body>
    <div id="title" class="container">
        <h1>Liste des activités pour le thème "<?php echo $this->_nameTheme ?>"</h1><br>
    </div>

    
    <section id="dashboard">
        <article>
            <?php echo $this->_listActivity ?>
        </article>
        <br><br><br><br><br><br><br><br><br><br>
    </section>
    <a href="./createActivity?idTheme=<?=$_GET['idTheme']?>&nTheme=<?=$_GET['nTheme']?>&colorTheme=<?=$_GET['colorTheme']?>"><input id="inputSubmit" style="width:30%;text-align: center;margin-left:35%" value="Créer une nouvelle activité"></a>
    <br><br>
    <a href="javascript:history.back()"><input id="inputSubmit" style="width: 20%;text-align: center;margin-left:40%" value="Retour"></a>
