<body>
    <div id="title" class="container">
        <h1>Liste des Session de formation</h1><br>
    </div>

    
    <section id="dashboard">
        <article>
            <?php echo $this->_sessionList ?>
        </article>
        <br><br><br><br><br><br><br><br><br><br>
    </section>
    <a id="inputSubmit" href="../../index.php/admin/createSession?nTraining=<?php echo $_GET['nTraining']?>" style='width:20%;text-align: center;margin-left:40%' "> Créer une session de formation </a><br><br> 

    <a href="javascript:history.back()"><input id="inputSubmit" style="width: 20%;text-align: center;margin-left:40%" value="Retour"></a>