<body>
    <div id="title" class="container">
        <h1>Liste des Thèmes</h1><br>
    </div>

    
    <section id="dashboard">
        <article>
            <?php echo $this->_listTheme ?>
        </article>
        <br><br><br><br><br><br><br><br><br><br>
    </section>
    <a id="inputSubmit" href="../../index.php/admin/createTheme" style="width:20%;text-align: center;margin-left:40%" > Créer un nouveau thème </a><br><br> 
