
<div id="title">
    <h3>Lien pour création d'un compte Administrateur</h3>
        </div>
            <div id="connexion">
                <form method="post">
                    <fieldset><br>
                        <label for="email">E-mail:</label><br>
                        <input type="email" id="email" name="mail"><br><br>
                        <input id="inputSubmit" type="submit" name="sendLinkAdmin" value="Envoyer"><br><br>
                </fieldset><br>
                <a id="inputSubmit" style="text-decoration: none;  margin-left: 10%;" href="../../index.php/admin/accountManagement"> Retour </a>
                </form>  
        </div>