<body>

<div id="registration" class="container">
        <fieldset>
            <h2> Mes Informations Personnelles </h2><br>
            <label style="font-size: 20px;">Prenom : <?php echo $this->_firstName?> </label><br>
            <label style="font-size: 20px;">Nom : <?php echo $this->_lastName?> </label><br>
            <label style="font-size: 20px;">Date de naissance : <?php echo $this->_birthDate?> </label><br>
            <br>
        <form method="post" action="index.php/collab/modifPhone">
            <label style="font-size: 20px;">Numero de telephone : <?php echo "0".$this->_phoneNumber?> </label><br>
            <label> Nouveau Numero : </label><br>
            <input type="tel" name="phoneNumber" pattern="0[1-68]([-. ]?[0-9]{2}){4}" title="Le numero de téléphone doit contenir 10 chiffres."><br>
            <input id="button" type="submit" name="modifPhone" value="Modifier"><br><br>
        </form>
        <form method="post" action="index.php/collab/modifMail">
            <label style="font-size: 20px;">E-mail : <?php echo $this->_mail?> </label><br>
            <label> Nouveau Mail : </label><br>
            <input type="email" name="mail"><br>
            <input id="button" type="submit" name="modifMail" value="Modifier"><br><br>
        </fieldset>
    </form>
</div>

