<div id="infoslot">
    <div id="infodesc"><?php echo $this->_infoSlot1;echo $this->_infoSlot2; ?></div>
<div><br></br>

<!--<a id="inputSubmit" href="../../index.php/anim/emargement?id_slot=<?=$_GET['idSlot']?>"> Imprimer Feuille d'Emargement </a><br><br>-->

<a id="inputSubmit" href="../../index.php/anim/presence?id_slot=<?=$_GET['idSlot']?>&id_activity=<?=$_GET['id_activity']?>"> Cocher les présences </a><br><br>

<a id="inputSubmit" href="../../index.php/anim/export?id_slot=<?=$_GET['idSlot']?>"> Imprimer Feuille de Présence </a><br><br>

<a id="inputSubmit" href="../../index.php/anim/dashboard"> Retour </a><br><br>

<form method="post">
    <input id="inputSubmit" style="background-color:red;" type="submit" onclick="return confirm('Etes-vous sûr de vouloir supprimer cette activité?')" name="deleteSlot" value = "Supprimer l'Activité">
</form>
