<div id="infoslot">
    <div id="infodesc"><?php echo $this->_infoSlot ?></div>
<div><br></br>

<!-- <button id="retour"><a id="retour" style="text-decoration: none;" href="http://www.lisae.fr:8081/index.php/collab/subscribe">Inscription</a></button><br></br>
<button id="retour"><a id="retour" style="text-decoration: none;" href="http://www.lisae.fr:8081/index.php/collab/unsubscribe">Desinscription</a></button><br></br> -->
<?php echo $this->_infoSlotButton ?>

<a id="retour" style="text-decoration: none;" href="http://www.lisae.fr:8081/index.php/anim/export"><button id="retour"> Imprimer Feuille de Présence </button></a>

<a id="retour" style="text-decoration: none;" href="http://www.lisae.fr:8081/index.php/anim/eloce"><button id="retour"> Retour </button></a>