
<div id="menu">
<h2>Inscription Administrateur</h2>
</div>

<div id="registration">
    <form method="post" id="form1">
            <label>Prenom :</label><br>
            <input type="text" name="firstname" pattern="[A-Z][a-z]+" title="Le prénom ne doit pas contenir de chiffres et doit commencer par une majuscule." required value="<?php if(isset($_POST['firstname'])){ echo $_POST['firstname']; }?>"><br>

            <label>Nom :</label><br>
            <input type="text" name="lastname" pattern="[A-Z][a-z]+" title="Le nom ne doit pas contenir de chiffres et doit commencer par une majuscule." required value="<?php if(isset($_POST['lastname'])){ echo $_POST['lastname']; }?>"><br>

            <label>Date de naissance :</label><br>
            <input type="date" name="birthdate"  required value="<?php if(isset($_POST['birthdate'])){ echo $_POST['birthdate']; }?>"><br>

            <label>Numero de telephone :</label><br>
            <input type="tel" name="phoneNumber" pattern="0[1-68]([-. ]?[0-9]{2}){4}" title="Le numero de téléphone doit contenir 10 chiffres." required value="<?php if(isset($_POST['phoneNumber'])){ echo $_POST['phoneNumber']; }?>"><br>

            <label>E-mail :</label><br>
            <input type="email" name="mail" required value="<?php if(isset($_POST['mail'])){ echo $_POST['mail']; }?>"><br>

            <label>Mot de passe :</label><br>
            <input type="password" name="password" pattern="(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{6,}" title="Le mot de passe doit comporter au minimum 6 caractères et contenir une majuscule, une minuscule et un chiffre." required><br>

            <label>Entrer le mot de passe à nouveau :</label><br>
            <input type="password" name="password2" pattern="(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{6,}" title="Le mot de passe doit comporter au minimum 6 caractères et contenir une majuscule, une minuscule et un chiffre." required><br><br>

            <input id="inputSubmit" style="width: 20%;" type="submit" name="registration" value="Valider"><br><br>
            <input id="inputSubmit" style="width: 20%;" type="reset" value="Annuler"><br><br><br>
    </form>
    <a id="inputSubmit" href="../../index.php">Connexion</a>
</div>