
<div id="title" class="container">
<h2>Inscription Collaborateur</h2>
</div>

<div id="registration" class="container">
    <form method="post">
        <fieldset>
            <label>Prenom :</label>
            <input type="text" name="firstname" pattern="[A-Z][a-z]+" title="Le prénom ne doit pas contenir de chiffres et doit commencer par une majuscule." required value="<?php if(isset($_POST['firstname'])){ echo $_POST['firstname']; }?>"><br>

            <label>Nom :</label>
            <input type="text" name="lastname" pattern="[A-Z][a-z]+" title="Le nom ne doit pas contenir de chiffres et doit commencer par une majuscule." required value="<?php if(isset($_POST['lastname'])){ echo $_POST['lastname']; }?>"><br>

            <label>Date de naissance :</label>
            <input type="date" name="birthdate"  required value="<?php if(isset($_POST['birthdate'])){ echo $_POST['birthdate']; }?>"><br>

            <label>Numero de telephone :</label>
            <input type="tel" name="phoneNumber" pattern="0[1-68]([-. ]?[0-9]{2}){4}" title="Le numero de téléphone doit contenir 10 chiffres." required value="<?php if(isset($_POST['phoneNumber'])){ echo $_POST['phoneNumber']; }?>"><br>

            <label>E-mail :</label>
            <input type="email" name="mail" required value="<?php if(isset($_POST['mail'])){ echo $_POST['mail']; }?>"><br>

            <label>Mot de passe :</label>
            <input type="password" name="password" pattern="(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{6,}" title="Le mot de passe doit comporter au minimum 6 caractères et contenir une majuscule, une minuscule et un chiffre." required><br>

            <label>Entrer le mot de passe à nouveau :</label>
            <input type="password" name="password2" pattern="(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{6,}" title="Le mot de passe doit comporter au minimum 6 caractères et contenir une majuscule, une minuscule et un chiffre." required><br><br>

            <label >Session de formation : </label>
            <select name="training">
                <?php echo $sessionList;?>
            </select>

            <input id="button" type="submit" name="registration" value="Valider"><br><br>
            <input id="button" type="reset" value="Annuler"><br>
        
        </fieldset><br><br>
    </form>
    <button id="button"><a id="button" href="../../index.php">Connexion</a></button>
</div>