<!DOCTYPE html>
    <html>
    <head>
        <title>Tableau de Bord</title>
    </head>

    <body>

        <h1>Tableau de Bord Collaborateur</h1>

        <div class="dashboard"><a href="/LISAE/view/collaborateurDashboard.phtml"> Mon Compte </a></div>

        <div class="activityTheme">

            <p>Activité par Thémes</p>

        </div>

        <div id="calendar">

        </div>

        <div id="myRDV">

        </div>

        

    </body>
    </html>