<!DOCTYPE html>
    <html>
        <head>
            <title>Login Page</title>
        </head>

    <body>

        <h1>Login Page</h1>

        <div id="connexion">
        <fieldset>
            <form action="/LISAE/index.php?action=registrationCollab" method="post">
                <label for="email">E-mail:</label><br>
                <input type="text" id="email" name="email"><br>
                <label for="mdp">Mot de passe:</label><br>
                <input type="text" id="mdp" name="mdp"><br><br>
                <input type="submit" value="Connexion">
                <button class="buttonRegistration"> Inscription </button>
            </form>
        </fieldset>    
        </div>

    </body>
    </html>