<?php require 'header.php' ?>

        <h1>Login Page</h1>

        <div id="connexion">
        <fieldset>
            <form action="index.php?action=checkConnection" method="post">
                <label for="email">E-mail:</label><br>
                <input type="email" id="email" name="mail"><br>
                <label for="mdp">Mot de passe:</label><br>
                <input type="password" id="mdp" name="password"><br><br>
                <input type="submit" value="Connexion">
            </form><br>

                <button value="Inscription"><a href="index.php?action=registrationCollab"> Inscription </a></button>

        </fieldset>    
        </div>

<?php require 'footer.php' ?>