<!DOCTYPE html>
    <html>
        <head>
            <title>Inscription Collaborateur</title>
        </head>

    <body>

        <h1>Inscription Collaborateur</h1>

        //formulaire collab
        <fieldset>
            <form action="index.php?" method="post">

                <label>Prenom :</label>
                <input type="text">

                <label>Nom :</label>
                <input type="text">

                <label>Date de naissance :</label>
                <input type="date">

                <label>Numero de telephone :</label>
                <input type="number">

                <label>E-mail :</label>
                <input type="email">

                <label>Mot de passe :</label>
                <input type="password">

            </form>
        </fieldset>

    </body>
    </html>