<!DOCTYPE html>
    <html>
    <head>
        <title>Inscription Atelier</title>
    </head>

    <body>

        <h1>Inscription Atelier</h1>

        <div class="dashboard"><a href="/LISAE/view/collaborateurDashboard.phtml"> Mon Compte </a></div>

        <div class="activity"></div>

        <button value="Retour"><a href="/LISAE/view/collaborateurDashboard.phtml"> Retour </a></button>

    </body>
    </html>