<!DOCTYPE html>
    <html>
        <head>
            <title>Inscription Animateur</title>
        </head>
    <body>
        <h1>Inscription Animateur</h1>
        <fieldset>
            <form class="formulaire" action="index.php?" method = "post">
                <label for="FirstName"> Nom :</label>
                <input type="texte"/>

                <label for="LastName"> Prenom :</label>
                <input type="texte"/>

                <label for="birthDate"> Date de naissance (Mois/Jour) :</label>
                <input type="date"/>

                <label for="PhoneNumber"> Numero de téléphone :</label>
                <input type="tel"/>

                <label for="mail"> Mail :</label>
                <input type="email"/>

                <label>Mot de passe :</label>
                <input type="password">

                <button type="submit"  value="creer">Créer</button>    
            </form>
            </fieldset>
            <a href="index.php">Retourner à l'accueil</a>  
    </body>
</html>