<!DOCTYPE html>
    <html>
        <head>
            <title>Inscription Administrateur</title>
        </head>

    <body>

        <h1>Inscription Administrateur</h1>

        <fieldset>
            <form class="formulaire" action="index.php?action=addAdmin" method = "post">
            <label>Prenom :</label>
                <input type="text" name="firstname"><br><br>

                <label>Nom :</label>
                <input type="text" name="lastname"><br><br>

                <label>Date de naissance :</label>
                <input type="date" name="birthdate"><br><br>

                <label>Numero de telephone :</label>
                <input type="number" name="phoneNumber"><br><br>

                <label>E-mail :</label>
                <input type="email" name="mail"><br><br>

                <label>Mot de passe :</label>
                <input type="password" name="password"><br><br>

                <input type="submit" value="Valider">
                <input type="reset" value="Annuler">    
            </form>
        </fieldset>
        <a href="index.php">Retourner à l'accueil</a>  

    </body>
    </html>