<!DOCTYPE html>
    <html>
    <head>
        <title>Atelier par théme</title>
    </head>

    <body>

        <h1>Atelier par théme</h1>
        
        <div class="dashboard"><a href="/LISAE/view/collaborateurDashboard.phtml"> Mon Compte </a></div>

        <h2>SOFT SKILLS</h2>
        <h2>CIBLE JOB 2.0</h2>
        <h2>Conférence</h2>

        <div class="description"></div>

        <button value="Retour"><a href="/LISAE/view/collaborateurDashboard.phtml"> Retour </a></button>

    </body>
    </html>